import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "../config/ApolloWrapper";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Voltron",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          {/* <main className='mx-auto flex min-h-screen  flex-col flex-wrap gap-10 px-6 md:py-12 py-4 md:gap-16'> */}
          <Navbar />
          {children}
          {/* </main> */}
        </ApolloWrapper>
      </body>
    </html>
  );
}
